# Read the Docs configuration file for phabfive
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      # Install uv for fast dependency management
      - pip install uv
    post_install:
      # Install project dependencies with uv
      - uv pip install --system -e ".[docs]"
      # Build the MkDocs site
      - mkdocs build --verbose --site-dir $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
