sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -e '.[test]'
script: 
  - pytest
matrix:
  allow_failures:
    - python: "nightly"
notifications:
  slack:
    secure: Q/GTFukazYNlmn6UdAqx2bklfsjdN433LRh2GwFDuGktJAZzbBaD6BFoOOA9ItwMYcQ+uzldKyNRAprSNxDbG04PzLo/MEY5lJeQ2CNQbZGyqdLITkC3jtdzjfbe/UEOea5sj+bPgzhONrgTf/D4aKHmTmXJ42hKZ9SOjNN2ecTYQQEXsmzDY3dXHBxpiyQs5p5sBABcdTO32lO49vvjkWr0Uvavqnnac0yy50gnMM0RQg9e1WqIG1tNxNiOmPpT+hUhoCgNSy/NmZ75bJgdhIrXJgh/aU2L4WGLP3r4gg3p5o0D83SiLTg+3B6+pu4KUXBKpopDmzjzH5OnS4XdI682kyheuTUtJAh8249BHRJBBlM5ONB6IzRcEgxCKK0l/KcFkgWXe379BltL4d/hf89VquWxfLrqmvZrRUyVTG5JYLRQZFmVoFnEVe+inhKM3ieSPpzLl1FCwdybJ9ASQaOU4jXeyF1K2it+dzM4MABzfToXIYnjchU11Sh72OUh3ow/pcShaQNsqcRV4AB6GiMxKDYc0QhBk5P3adhMPlUUJrU6RysWozkHjIIF1yIjb46S7DGkov1CjpepZs2y2UHbs92O4HxvKOco0cM4COt2zppEBi5hmtaBK+3LDuzbI0VmWLiKJQlBNOr+ErdWrKNW3/uUplD3ydc/Nz/7mrw=
