version: '3.7'
services:
  mysql:
    image: 'nasqueron/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=somerootpassword
  phabricator:
    image: 'nasqueron/phabricator'
    environment:
      - PHABRICATOR_URL="http://phabricator.domain.tld"
      - PHABRICATOR_TITLE="Acme"
      - PHABRICATOR_ALT_FILE_DOMAIN="files-for-phabricator.anotherdomain.tld"
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=somerootpassword
    ports:
      - '81:80'
    depends_on:
      - mysql
