.PHONY: help clean cleancov cleanegg cleanpy cleanall cleantox test install

# http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


clean: ## remove temporary files created by build tools
	-rm -f MANIFEST
	-rm -rf dist/
	-rm -rf build/

cleancov: ## remove files used and generated by coverage tools
	coverage combine || true
	coverage erase || true
	-rm -rf htmlcov/

cleanegg: ## remove temporary files created by build tools
	-rm -rf unifik.egg-info/

cleanpy: ## remove temporary python files
	-find . -type f -name "*~" -exec rm -f "{}" \;
	-find . -type f -name "*.orig" -exec rm -f "{}" \;
	-find . -type f -name "*.rej" -exec rm -f "{}" \;
	-find . -type f -name "*.pyc" -exec rm -f "{}" \;
	-find . -type f -name "*.parse-index" -exec rm -f "{}" \;
	-find . -type d -name "__pycache__" -exec rm -rf "{}" \;

cleanall: clean cleanegg cleanpy cleancov ## all the above + tmp files from development tools (not cleantox)

cleantox: ## remove files created by tox
	-rm -rf .tox/

test: ## run test suite
	coverage erase
	tox --skip-missing-interpreters
	coverage combine
	coverage report

sdist: ## make a source distribution
	python setup.py sdist

snap: ## make a snap package
	snapcraft cleanbuild

install: ## install package
	python setup.py install
