---
site_name: Phabfive
theme: readthedocs
repo_url: https://github.com/dynamist/phabfive

nav:
    - Introduction: 'index.md'
    - Maniphest CLI: 'maniphest-cli.md'
    - Development: 'development.md'
    - Phorge Setup: 'phorge-setup.md'
    - Release Process: 'releasing.md'

watch:
  - docs

markdown_extensions:
    - admonition:
