[tool.poetry]
name = "phabfive"
version = "0.1.0"
description = ""
authors = ["Henrik Holmboe <henrik@dynamist.se>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^4.5"
