apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Test the Phorge and Arcanist baked into the image, without fetching at start
configMapGenerator:
  - name: phorge-config
    behavior: merge
    literals:
      - PHORGE_GIT_REF=
      - ARCANIST_GIT_REF=
