---
name: Secrets

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "25 7 * * Mon"  # run every week on Mondays at 07:25

jobs:
  scan:
    name: trufflehog
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@f714bf454f350590f4a24c3ddb1aef02c35bf5b6 # v3.97.5
        with:
          extra_args: --results=verified,unknown
