name: Tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: >-
      ${{ matrix.os }} v${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        include:
          - os: windows-latest
            python-version: "3.9"
            experimental: true
          - os: windows-latest
            python-version: "3.10"
            experimental: true
          - os: windows-latest
            python-version: "3.11"
            experimental: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install '.[test]'

      - name: Test with tox
        run: tox run --quiet
